#scenarios
question1 = ("A 40yo woman currently on chemotherapy, with a temperature of 102F. What level of triage is this?")
question2 = ("A 5yo has sudden onset of left foot pain. They have a history of diabetes requiring insulin and their left foot cold to touch- no pulses. What level triage would you place this?")
question3 = ("A 19yo male brought in by police, with ETOH on breath, an unsteady gait, large head lac, and slurred speech but oriented. What level triage would you place this?")
question4 = ("A 24yo patient is brought in with severe respiratory distress. Their SPo2 is 80%. What level triage would you place this?")
question5 = ("A woman brings in her 3yo child who fell down the steps. THey are unresponsive to a sternal rub. What level of triage is this?")
question6 = ("A healthy 52yo man is brought into the ED. He ran out of BP medication and his blood pressure is 150/92. What level triage would you place this?")
question7 = ("A 12yo girl is brought into the ED with poison ivy. What level triage would you place this?")
question8 = ("A 19yo boy is brought in with a sore throat and fever. What level triage would you place this?")
question9 = ("A 29yo woman is brought into the ED with a UTI. What level triage would you place this?")
question10 =("A 22-year-old is brought into the ED with right LLQ pain since early am and nausea. They have no appetite. What level triage would you place this?\n")
question11 = ("A 45-yr old obese female comes to the ED with complaints of LLE pain/swelling. IT started 2 days ago after driving for 12 hrs What level triage would you place this?\n")
#answer portion still needs to be filled
answer1 = ("Level 2")
answer2 = ("Level 2")
answer3 = ("Level 2")
answer4 = ("Level 1")
answer5 = ("Level 1")
answer6 = ("Level 5")
answer7 = ("Level 5")
answer8 = ("Level 4")
answer9 = ("Level 4")
answer10 = ("Level 3")
answer11 = ("Level 3")
